// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh7FwUWICRHe7d38y_ygMjEz7td6ybaMw',
    appId: '1:302473781383:web:043164502427eda01d5822',
    messagingSenderId: '302473781383',
    projectId: 'kasir-gen',
    authDomain: 'kasir-gen.firebaseapp.com',
    storageBucket: 'kasir-gen.firebasestorage.app',
    measurementId: 'G-4GBW1VFYDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfA8EdskSTIYNBboknFMwGvWTuMCrs1Ps',
    appId: '1:302473781383:android:c2111bc1ec7e05791d5822',
    messagingSenderId: '302473781383',
    projectId: 'kasir-gen',
    storageBucket: 'kasir-gen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhilBWkr6P4eCPdBOYAYR79o-BGVkv0PU',
    appId: '1:302473781383:ios:1735cbf886032acd1d5822',
    messagingSenderId: '302473781383',
    projectId: 'kasir-gen',
    storageBucket: 'kasir-gen.firebasestorage.app',
    iosBundleId: 'com.example.kasirGen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh7FwUWICRHe7d38y_ygMjEz7td6ybaMw',
    appId: '1:302473781383:web:9ef787143f1356e31d5822',
    messagingSenderId: '302473781383',
    projectId: 'kasir-gen',
    authDomain: 'kasir-gen.firebaseapp.com',
    storageBucket: 'kasir-gen.firebasestorage.app',
    measurementId: 'G-SPXCNFWJPH',
  );
}
