// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6yHgzMiz7aWnbcu4650sA4ioKsoARF20',
    appId: '1:556265980791:web:128d3ee0a1872140641772',
    messagingSenderId: '556265980791',
    projectId: 'kasir-gen-live',
    authDomain: 'kasir-gen-live.firebaseapp.com',
    storageBucket: 'kasir-gen-live.firebasestorage.app',
    measurementId: 'G-FF03SSM2WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLZreHVIYPbAONbc7vryJcuvpGf8Fc7Q',
    appId: '1:556265980791:android:da9ec32952e1dbe2641772',
    messagingSenderId: '556265980791',
    projectId: 'kasir-gen-live',
    storageBucket: 'kasir-gen-live.firebasestorage.app',
  );
}
